version: '3.8'
services:
  app:
    container_name: metatrader_${FOLDER_NAME}
    image: lucaorioli/metatrader5:current
    restart: unless-stopped
    ports:
      - '990${FOLDER_NAME}:5900'
      - '1${FOLDER_NAME}55:15555'
      - '1${FOLDER_NAME}56:15556'
      - '1${FOLDER_NAME}57:15557'
      - '1${FOLDER_NAME}58:15558'
    volumes:
      - ./data:/data
      - ./Metatrader:/root/Metatrader
    environment:
      - PW_VNC=default_pw_vnc
    networks:
      mynetwork:
        ipv4_address: 172.${FOLDER_NAME}.0.2
networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.${FOLDER_NAME}.0.0/16
