version: '3.8'
services:
  app:
    container_name: metatrader
    image: lucaorioli/metatrader5:current
    restart: unless-stopped
    ports:
      - '15001:5900'
      - '15555:15555'
      - '15556:15556'
      - '15557:15557'
      - '15558:15558'
    volumes:
      - ./data:/data
      - ./Metatrader:/root/Metatrader
    command: >
      sh -c 'if [ ! -d "/root/Metatrader" ]; then 
                 if [ -f "/root/Metatrader.zip" ]; then
                     unzip -q /root/Metatrader.zip -d /root
                 fi
             fi && exec my_start_command'
    networks:
      mynetwork:
        ipv4_address: 172.1.0.2

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.1.0.0/16
